[package]
name = "aa"
version = "0.1.0"
cairo-version = "2.3.1"

[dependencies]
starknet = ">=2.3.1"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.11.0" }

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
test = "snforge test"